name: main_test

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (simple_window)
      run: cargo build --verbose
      working-directory: ./simple_window
    - name: Build (simple_draw)
      run: cargo build --verbose
      working-directory: ./simple_draw
    - name: Run tests (simple_draw)
      run: cargo test --verbose
      working-directory: ./simple_draw
    - name: Build (simple_triangle)
      run: cargo build --verbose
      working-directory: ./simple_triangle
    - name: Run tests (simple_triangle)
      run: cargo test --verbose
      working-directory: ./simple_triangle
    - name: Build (simple_texture)
      run: cargo build --verbose
      working-directory: ./simple_texture
    - name: Run tests (simple_texture)
      run: cargo test --verbose
      working-directory: ./simple_texture
    - name: Build (shadow_map)
      run: cargo build --verbose
      working-directory: ./shadow_map
    - name: Run tests (shadow_map)
      run: cargo test --verbose
      working-directory: ./shadow_map
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-binaries
        path: ${{ github.workspace }}/**/*.exe
        if-no-files-found: error
